.PHONY: help up down build test lint dev agent-run clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

# --- Docker Compose ---

up: ## Start all services (MongoDB + API + Dashboard)
	docker compose up -d --build

down: ## Stop all services
	docker compose down

reset: ## Stop all services and remove volumes
	docker compose down -v

logs: ## Follow logs from all services
	docker compose logs -f

logs-api: ## Follow API logs
	docker compose logs -f api

# --- Build ---

build: build-agent build-api ## Build all Go binaries

build-agent: ## Build the DecisionBox Agent
	cd services/agent && go build -o ../../bin/decisionbox-agent .

build-api: ## Build the DecisionBox API
	cd services/api && go build -o ../../bin/decisionbox-api .

build-dashboard: ## Build the Dashboard
	cd ui/dashboard && npm run build

# --- Test ---

test: test-go test-ui ## Run all tests

test-go: ## Run Go unit tests
	cd libs/go-common && go test ./...
	cd libs/awscreds && go test ./...
	cd libs/gcpcreds && go test ./...
	cd providers/llm/claude && go test ./...
	cd providers/llm/openai && go test ./...
	cd providers/llm/ollama && go test ./...
	cd providers/llm/vertex-ai && go test ./...
	cd providers/llm/bedrock && go test ./...
	cd providers/llm/azure-foundry && go test ./...
	cd providers/secrets/mongodb && go test ./...
	cd providers/secrets/gcp && go test ./...
	cd providers/secrets/aws && go test ./...
	cd providers/secrets/azure && go test ./...
	cd providers/warehouse/bigquery && go test ./...
	cd providers/warehouse/databricks && go test ./...
	cd providers/warehouse/mssql && go test ./...
	cd providers/warehouse/redshift && go test ./...
	cd providers/warehouse/postgres && go test ./...
	cd providers/warehouse/snowflake && go test ./...
	cd providers/embedding/azure-openai && go test ./...
	cd providers/embedding/bedrock && go test ./...
	cd providers/embedding/openai && go test ./...
	cd providers/embedding/ollama && go test ./...
	cd providers/embedding/vertex-ai && go test ./...
	cd providers/embedding/voyage && go test ./...
	cd libs/go-common/vectorstore/qdrant && go test ./...
	cd services/agent && go test ./...
	cd services/api && go test ./...

test-integration: ## Run integration tests (requires Docker)
	cd services/agent && go test -tags=integration -count=1 .
	cd services/agent && go test -tags=integration -count=1 ./internal/database/
	cd services/agent && go test -tags=integration -count=1 -timeout=5m ./internal/discovery/
	cd services/api && go test -tags=integration -count=1 .
	cd services/api && go test -tags=integration -count=1 ./database/
	cd services/api && go test -tags=integration -count=1 -timeout=5m ./internal/handler/
	cd services/api && go test -tags=integration -count=1 -timeout=5m ./internal/server/

test-k8s: ## Run K8s runner integration tests (requires Docker, uses K3s testcontainer)
	cd services/api && go test -tags=integration -count=1 -timeout=5m ./internal/runner/

test-secrets: ## Run secrets provider integration tests (MongoDB: Docker, GCP/AWS: credentials)
	@echo "Secret provider integration tests."
	@echo "  MongoDB                              → always runs (uses Docker/testcontainers)"
	@echo "  INTEGRATION_TEST_GCP_PROJECT_ID      → GCP Secret Manager (needs GCP ADC)"
	@echo "  INTEGRATION_TEST_AWS_REGION           → AWS Secrets Manager (needs AWS creds)"
	@echo "  INTEGRATION_TEST_AZURE_VAULT_URL     → Azure Key Vault (needs Azure creds)"
	@echo ""
	cd providers/secrets/mongodb && go test -tags=integration -count=1 -v ./...
	cd providers/secrets/gcp && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/secrets/aws && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/secrets/azure && go test -tags=integration -count=1 -timeout=2m -v ./...

test-qdrant: ## Run Qdrant integration tests (requires Docker, uses testcontainer)
	cd libs/go-common/vectorstore/qdrant && go test -tags=integration_qdrant -count=1 -timeout=2m -v ./...

test-embedding: ## Run embedding provider tests
	cd providers/embedding/azure-openai && go test -v ./...
	cd providers/embedding/bedrock && go test -v ./...
	cd providers/embedding/openai && go test -v ./...
	cd providers/embedding/ollama && go test -v ./...
	cd providers/embedding/vertex-ai && go test -v ./...
	cd providers/embedding/voyage && go test -v ./...

test-embedding-integration: ## Run embedding provider integration tests (set INTEGRATION_TEST_* env vars)
	@echo "Embedding integration tests — skips providers without credentials."
	@echo "  INTEGRATION_TEST_OPENAI_API_KEY                    → OpenAI"
	@echo "  INTEGRATION_TEST_VOYAGE_API_KEY                    → Voyage AI"
	@echo "  INTEGRATION_TEST_VERTEX_PROJECT_ID                 → Vertex AI (needs GCP ADC)"
	@echo "  INTEGRATION_TEST_BEDROCK_REGION                    → Bedrock (needs AWS creds)"
	@echo "  INTEGRATION_TEST_AZURE_OPENAI_ENDPOINT + _API_KEY + _DEPLOYMENT → Azure OpenAI"
	@echo ""
	cd providers/embedding/openai && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/embedding/voyage && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/embedding/vertex-ai && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/embedding/bedrock && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/embedding/azure-openai && go test -tags=integration -count=1 -timeout=2m -v ./...

test-postgres: ## Run PostgreSQL integration tests (requires Docker, uses testcontainer)
	cd providers/warehouse/postgres && go test -tags=integration_postgres -count=1 -timeout=5m -v ./...

test-mssql: ## Run Microsoft SQL Server integration tests (requires Docker, uses testcontainer)
	@echo "MSSQL integration tests — uses testcontainers-mssql by default."
	@echo "  Override with external server: INTEGRATION_TEST_MSSQL_HOST + _PASSWORD (+ _USER, _DATABASE, _SCHEMA, _PORT, _ENCRYPT, _TRUST_CERT)"
	@echo ""
	cd providers/warehouse/mssql && go test -tags=integration_mssql -count=1 -timeout=10m -v ./...

test-databricks: ## Run Databricks integration tests (set INTEGRATION_TEST_DATABRICKS_* env vars)
	@echo "Databricks integration tests."
	@echo "  INTEGRATION_TEST_DATABRICKS_HOST      → workspace hostname"
	@echo "  INTEGRATION_TEST_DATABRICKS_HTTP_PATH  → SQL warehouse path"
	@echo "  INTEGRATION_TEST_DATABRICKS_TOKEN      → personal access token"
	@echo "  INTEGRATION_TEST_DATABRICKS_CATALOG    → catalog (default: samples)"
	@echo "  INTEGRATION_TEST_DATABRICKS_SCHEMA     → schema (default: nyctaxi)"
	@echo ""
	cd providers/warehouse/databricks && go test -tags=integration_databricks -count=1 -timeout=5m -v ./...

test-ollama: ## Run Ollama LLM integration tests (requires Docker, slow)
	cd services/agent && go test -tags='integration ollama' -count=1 -timeout=10m -run TestOllama .

test-llm: ## Run LLM provider integration tests (set INTEGRATION_TEST_* env vars, see below)
	@echo "LLM integration tests — skips providers without credentials."
	@echo "  INTEGRATION_TEST_ANTHROPIC_API_KEY  → Claude (direct)"
	@echo "  INTEGRATION_TEST_OPENAI_API_KEY     → OpenAI"
	@echo "  INTEGRATION_TEST_VERTEX_PROJECT_ID  → Vertex AI (needs GCP ADC)"
	@echo "  INTEGRATION_TEST_BEDROCK_REGION     → Bedrock (needs AWS creds)"
	@echo "  INTEGRATION_TEST_AZURE_FOUNDRY_ENDPOINT + _API_KEY → Azure AI Foundry"
	@echo ""
	cd providers/llm/claude && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/llm/openai && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/llm/vertex-ai && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/llm/bedrock && go test -tags=integration -count=1 -timeout=2m -v ./...
	cd providers/llm/azure-foundry && go test -tags=integration -count=1 -timeout=2m -v ./...

test-ui: ## Run dashboard tests
	cd ui/dashboard && npm test

# --- Lint ---

lint: lint-go lint-ui ## Run all linters

lint-go: ## Run golangci-lint on all Go modules (install: https://golangci-lint.run/welcome/install/)
	cd libs/go-common && golangci-lint run ./...
	cd libs/awscreds && golangci-lint run ./...
	cd libs/gcpcreds && golangci-lint run ./...
	cd providers/warehouse/databricks && golangci-lint run ./...
	cd providers/warehouse/mssql && golangci-lint run ./...
	cd providers/warehouse/postgres && golangci-lint run ./...
	cd providers/warehouse/redshift && golangci-lint run ./...
	cd providers/warehouse/snowflake && golangci-lint run ./...
	cd providers/secrets/azure && golangci-lint run ./...
	cd providers/embedding/azure-openai && golangci-lint run ./...
	cd providers/embedding/bedrock && golangci-lint run ./...
	cd providers/embedding/openai && golangci-lint run ./...
	cd providers/embedding/ollama && golangci-lint run ./...
	cd providers/embedding/vertex-ai && golangci-lint run ./...
	cd providers/embedding/voyage && golangci-lint run ./...
	cd libs/go-common/vectorstore/qdrant && golangci-lint run ./...
	cd services/agent && golangci-lint run ./...
	cd services/api && golangci-lint run ./...

lint-ui: ## Run ESLint on dashboard
	cd ui/dashboard && npm run lint

# --- Development ---

dev-api: ## Run API locally (requires MongoDB on localhost:27017)
	cd services/api && MONGODB_URI=mongodb://localhost:27017 MONGODB_DB=decisionbox go run .

dev-dashboard: ## Run Dashboard locally
	cd ui/dashboard && npm run dev

agent-run: ## Run discovery agent for a project (usage: make agent-run PROJECT_ID=xxx)
	cd services/agent && go run . --project-id=$(PROJECT_ID)

# --- Docker ---

REGISTRY ?= ghcr.io/decisionbox-io
TAG ?= latest

docker-build: docker-build-api docker-build-agent docker-build-dashboard ## Build all Docker images

docker-build-api: ## Build API Docker image
	docker build -t $(REGISTRY)/decisionbox-api:$(TAG) -f services/api/Dockerfile .

docker-build-agent: ## Build Agent Docker image
	docker build -t $(REGISTRY)/decisionbox-agent:$(TAG) -f services/agent/Dockerfile .

docker-build-dashboard: ## Build Dashboard Docker image
	docker build -t $(REGISTRY)/decisionbox-dashboard:$(TAG) -f ui/dashboard/Dockerfile ui/dashboard

docker-push: ## Push all Docker images to registry
	docker push $(REGISTRY)/decisionbox-api:$(TAG)
	docker push $(REGISTRY)/decisionbox-agent:$(TAG)
	docker push $(REGISTRY)/decisionbox-dashboard:$(TAG)

# --- Clean ---

clean: ## Remove build artifacts
	rm -rf bin/
	rm -rf ui/dashboard/.next
