package handler

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"

	gollm "github.com/decisionbox-io/decisionbox/libs/go-common/llm"
	"github.com/decisionbox-io/decisionbox/libs/go-common/llm/modelcatalog"
	"github.com/decisionbox-io/decisionbox/libs/go-common/policy"
	"github.com/decisionbox-io/decisionbox/libs/go-common/secrets"
	"github.com/decisionbox-io/decisionbox/libs/go-common/telemetry"
	"github.com/decisionbox-io/decisionbox/services/api/database"
	apilog "github.com/decisionbox-io/decisionbox/services/api/internal/log"
	"github.com/decisionbox-io/decisionbox/services/api/models"
)

// validateLLMConfig surfaces malformed llm.config values at write time so a
// typo like wire_override="antropik" is rejected by the API instead of
// being accepted and then failing at agent-run time with a less obvious
// error.
//
// When provider is non-empty and has a registered wire_override
// ConfigField with Options, the accepted values are scoped to that
// provider's supported wires (e.g. bedrock only offers anthropic +
// openai-compat). Otherwise we fall back to the generic catalog-wide
// parse so providers that don't register options still get syntax
// validation. Returns a user-facing message on failure, or "" on pass.
func validateLLMConfig(provider string, cfg map[string]string) string {
	raw, ok := cfg["wire_override"]
	if !ok || raw == "" {
		return ""
	}

	// Provider-scoped check: if the provider exposes wire_override as a
	// dropdown, use its Options as the authoritative allowlist.
	if provider != "" {
		if meta, ok := gollm.GetProviderMeta(provider); ok {
			for _, f := range meta.ConfigFields {
				if f.Key != "wire_override" || len(f.Options) == 0 {
					continue
				}
				for _, o := range f.Options {
					if o.Value == raw {
						return ""
					}
				}
				accepted := make([]string, 0, len(f.Options))
				for _, o := range f.Options {
					if o.Value != "" {
						accepted = append(accepted, o.Value)
					}
				}
				return fmt.Sprintf(
					"llm.config.wire_override: %q is not supported by provider %q; use one of %s",
					raw, provider, strings.Join(accepted, ", "),
				)
			}
		}
	}

	// Fallback: generic wire-syntax check.
	if !modelcatalog.ParseWire(raw).Valid() {
		return fmt.Sprintf(
			"llm.config.wire_override: %q is not a valid wire; use one of %s, %s, %s",
			raw, modelcatalog.Anthropic, modelcatalog.OpenAICompat, modelcatalog.GoogleNative,
		)
	}
	return ""
}

// ProjectsHandler handles project CRUD endpoints.
type ProjectsHandler struct {
	repo            database.ProjectRepo
	domainPackRepo  database.DomainPackRepo
	dropper         CollectionDropper      // optional: Qdrant per-project collection
	secretProvider  secrets.Provider       // optional: only mongo-backed providers get swept
	indexCanceller  IndexCanceller         // optional: detect in-flight indexing for 409
}

func NewProjectsHandler(repo database.ProjectRepo, domainPackRepo database.DomainPackRepo) *ProjectsHandler {
	return &ProjectsHandler{repo: repo, domainPackRepo: domainPackRepo}
}

// WithDeleteCascadeDeps attaches the optional dependencies the Delete
// endpoint needs to fully wipe a project (Qdrant collection drop,
// secret sweep, in-flight detection). All three are nullable — when
// any is nil, that subsystem's cleanup step is skipped, which matches
// the community Qdrant-less / external-secret-manager builds.
func (h *ProjectsHandler) WithDeleteCascadeDeps(dropper CollectionDropper, secretProvider secrets.Provider, indexCanceller IndexCanceller) *ProjectsHandler {
	h.dropper = dropper
	h.secretProvider = secretProvider
	h.indexCanceller = indexCanceller
	return h
}

// Create creates a new project.
// POST /api/v1/projects
func (h *ProjectsHandler) Create(w http.ResponseWriter, r *http.Request) {
	var p models.Project
	if err := decodeJSON(r, &p); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}

	if p.Name == "" {
		writeError(w, http.StatusBadRequest, "name is required")
		return
	}

	// Pack-gen wizard: when generate_pack.enabled is set, the pack the
	// project will use does not exist yet — it is generated by the agent
	// after the user fills the wizard. The dashboard creates the project
	// with empty domain/category/prompts and a generate_pack payload; the
	// caller transitions the project through pack_generation_pending →
	// pack_generation → pack_generation_done → ready, attaching a real
	// domain pack at the end.
	wizardMode := p.GeneratePack != nil && p.GeneratePack.Enabled
	if wizardMode {
		if p.GeneratePack.PackName == "" {
			writeError(w, http.StatusBadRequest, "generate_pack.pack_name is required")
			return
		}
		if p.GeneratePack.PackSlug == "" {
			writeError(w, http.StatusBadRequest, "generate_pack.pack_slug is required")
			return
		}
		if len(p.GeneratePack.PackSlug) < 2 || !slugRegexp.MatchString(p.GeneratePack.PackSlug) {
			writeError(w, http.StatusBadRequest, "generate_pack.pack_slug must be lowercase alphanumeric with hyphens")
			return
		}
		// Conflict check: the wizard cannot pick a slug that's already taken.
		// Other failure modes (Mongo down, etc.) bubble up as 500.
		if h.domainPackRepo != nil {
			existing, err := h.domainPackRepo.GetBySlug(r.Context(), p.GeneratePack.PackSlug)
			if err != nil {
				writeError(w, http.StatusInternalServerError, "failed to check pack slug: "+err.Error())
				return
			}
			if existing != nil {
				writeError(w, http.StatusConflict, "domain pack already exists with slug: "+p.GeneratePack.PackSlug)
				return
			}
		}
		// Lock state — caller cannot pre-set state to anything else.
		p.State = models.ProjectStatePackGenerationPending
		// Domain + category get filled in later when the generated pack
		// is persisted; clear anything the caller sent so the rest of the
		// pipeline sees a consistent shape.
		p.Domain = ""
		p.Category = ""
		p.Prompts = nil
	} else {
		if p.Domain == "" {
			writeError(w, http.StatusBadRequest, "domain is required")
			return
		}
		if p.Category == "" {
			writeError(w, http.StatusBadRequest, "category is required")
			return
		}
		// Default state for non-wizard projects so the field is always
		// meaningful for downstream code (legacy projects with empty
		// State are still treated as ready by EffectiveState).
		if p.State == "" {
			p.State = models.ProjectStateReady
		}
	}

	if msg := validateLLMConfig(p.LLM.Provider, p.LLM.Config); msg != "" {
		writeError(w, http.StatusBadRequest, msg)
		return
	}

	// Seed default prompts from domain pack — only for non-wizard
	// projects; the wizard generates its own pack later.
	if !wizardMode && p.Prompts == nil && h.domainPackRepo != nil {
		pack, err := h.domainPackRepo.GetBySlug(r.Context(), p.Domain)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "failed to load domain pack: "+err.Error())
			return
		}
		if pack == nil {
			writeError(w, http.StatusBadRequest, "domain pack not found: "+p.Domain)
			return
		}
		SeedProjectPrompts(&p, pack)
	}

	// Plan-gate: provider allow-list. Self-hosted Noop permits everything.
	ck := policy.GetChecker()
	if err := ck.CheckLLMProviderAllowed(r.Context(), "", p.LLM.Provider); err != nil {
		if writePolicyError(w, err) {
			return
		}
		writeError(w, http.StatusInternalServerError, "policy check failed: "+err.Error())
		return
	}

	// Plan-gate: projects-per-deployment. Reservation is consumed on a
	// successful repo insert and released on failure.
	res, err := ck.CheckCreateProject(r.Context(), "", policy.ProjectIntent{
		ProjectID:   p.ID,
		Name:        p.Name,
		LLMProvider: p.LLM.Provider,
	})
	if err != nil {
		if writePolicyError(w, err) {
			return
		}
		writeError(w, http.StatusInternalServerError, "policy check failed: "+err.Error())
		return
	}

	// Plan-gate: data-sources-per-deployment. A project today carries
	// exactly one warehouse (the data-source unit), so adding a project
	// that configures a warehouse is also adding a data source.
	// Self-hosted Noop is a no-op.
	var dsRes *policy.Reservation
	if p.Warehouse.Provider != "" {
		dsRes, err = ck.CheckAddDataSource(r.Context(), "")
		if err != nil {
			if res != nil {
				if relErr := ck.Release(r.Context(), res.ID); relErr != nil {
					apilog.WithError(relErr).Warn("failed to release project-create reservation after data-source denial")
				}
			}
			if writePolicyError(w, err) {
				return
			}
			writeError(w, http.StatusInternalServerError, "policy check failed: "+err.Error())
			return
		}
	}

	if err := h.repo.Create(r.Context(), &p); err != nil {
		apilog.WithError(err).Error("Failed to create project")
		if res != nil {
			if relErr := ck.Release(r.Context(), res.ID); relErr != nil {
				apilog.WithError(relErr).Warn("failed to release project-create reservation after insert failure")
			}
		}
		if dsRes != nil {
			if relErr := ck.Release(r.Context(), dsRes.ID); relErr != nil {
				apilog.WithError(relErr).Warn("failed to release data-source reservation after insert failure")
			}
		}
		writeError(w, http.StatusInternalServerError, "failed to create project: "+err.Error())
		return
	}

	apilog.WithFields(apilog.Fields{
		"project_id": p.ID,
		"name":       p.Name,
		"domain":     p.Domain,
		"category":   p.Category,
		"llm":        p.LLM.Provider,
		"warehouse":  p.Warehouse.Provider,
	}).Info("Project created")

	telemetry.TrackProjectCreated(p.Warehouse.Provider, p.LLM.Provider, p.Domain)

	// Enqueue the new project for schema indexing. A project without a
	// warehouse (blank-state) cannot be indexed; it will transition to
	// pending_indexing on its first PUT that adds one. We set this
	// explicitly rather than defaulting in the repo so reads without a
	// warehouse still see SchemaIndexStatus == "" (→ "not yet
	// configured" in the dashboard). Wizard-mode projects skip indexing
	// here too — the wizard's warehouse step adds the warehouse, and
	// pack-gen runs schema indexing as part of its own flow.
	if !wizardMode && p.Warehouse.Provider != "" {
		if err := h.repo.SetSchemaIndexStatus(r.Context(), p.ID, models.SchemaIndexStatusPendingIndexing, ""); err != nil {
			apilog.WithError(err).Warn("schema-index: failed to enqueue new project; user must click Re-index manually")
		} else {
			p.SchemaIndexStatus = models.SchemaIndexStatusPendingIndexing
		}
	}

	writeJSON(w, http.StatusCreated, p)
}

// List returns all projects.
// GET /api/v1/projects
func (h *ProjectsHandler) List(w http.ResponseWriter, r *http.Request) {
	limit, _ := strconv.Atoi(r.URL.Query().Get("limit"))
	offset, _ := strconv.Atoi(r.URL.Query().Get("offset"))

	projects, err := h.repo.List(r.Context(), limit, offset)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to list projects: "+err.Error())
		return
	}

	if projects == nil {
		projects = make([]*models.Project, 0)
	}

	writeJSON(w, http.StatusOK, projects)
}

// Get returns a project by ID.
// GET /api/v1/projects/{id}
func (h *ProjectsHandler) Get(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")

	p, err := h.repo.GetByID(r.Context(), id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to get project: "+err.Error())
		return
	}
	if p == nil {
		writeError(w, http.StatusNotFound, "project not found")
		return
	}

	writeJSON(w, http.StatusOK, p)
}

// Update updates a project.
// PUT /api/v1/projects/{id}
// Merges incoming fields with existing project — preserves fields not in the request
// (e.g., settings page doesn't send prompts, prompts page doesn't send warehouse).
func (h *ProjectsHandler) Update(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")

	existing, err := h.repo.GetByID(r.Context(), id)
	if err != nil || existing == nil {
		writeError(w, http.StatusNotFound, "project not found")
		return
	}

	var incoming models.Project
	if err := decodeJSON(r, &incoming); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}

	// Plan-gate: if the request changes the LLM provider, validate the
	// new provider against the plan's allow-list before persisting.
	if incoming.LLM.Provider != "" && incoming.LLM.Provider != existing.LLM.Provider {
		if err := policy.GetChecker().CheckLLMProviderAllowed(r.Context(), "", incoming.LLM.Provider); err != nil {
			if writePolicyError(w, err) {
				return
			}
			writeError(w, http.StatusInternalServerError, "policy check failed: "+err.Error())
			return
		}
	}

	// Validate provider-specific LLM config (e.g., wire_override syntax).
	if incoming.LLM.Provider != "" {
		if msg := validateLLMConfig(incoming.LLM.Provider, incoming.LLM.Config); msg != "" {
			writeError(w, http.StatusBadRequest, msg)
			return
		}
	}

	// Merge: update only fields that are present in the request
	if incoming.Name != "" {
		existing.Name = incoming.Name
	}
	if incoming.Description != "" || incoming.Name != "" {
		existing.Description = incoming.Description
	}
	if incoming.Warehouse.Provider != "" {
		existing.Warehouse = incoming.Warehouse
	}
	if incoming.LLM.Provider != "" {
		existing.LLM = incoming.LLM
	}
	if incoming.Schedule.CronExpr != "" || incoming.Schedule.Enabled {
		existing.Schedule = incoming.Schedule
	}
	if incoming.Profile != nil {
		existing.Profile = incoming.Profile
	}
	if incoming.Prompts != nil {
		existing.Prompts = incoming.Prompts
	}
	if incoming.Embedding.Provider != "" {
		existing.Embedding = incoming.Embedding
	}
	// BlurbLLM is a pointer — nil means "field not present in this
	// request" (preserve existing), an empty-provider value means "user
	// cleared the override" (so we clear it too).
	if incoming.BlurbLLM != nil {
		if incoming.BlurbLLM.Provider == "" {
			existing.BlurbLLM = nil
		} else {
			existing.BlurbLLM = incoming.BlurbLLM
		}
	}

	// State: most lifecycle transitions go through dedicated endpoints
	// (POST /pack-generate flips to pack_generation; the orchestrator
	// flips to pack_generation_done; etc.). The ONE legitimate
	// state-change-via-PUT is the user accepting a generated pack —
	// pack_generation_done → ready — which the dashboard fires from
	// the "Accept and continue" / "Skip review" buttons. Allowing
	// arbitrary state writes would let any caller revert a project
	// back into pack-gen mid-flight; locking it to this single
	// transition keeps the state machine sound.
	if incoming.State == models.ProjectStateReady &&
		existing.State == models.ProjectStatePackGenerationDone {
		existing.State = models.ProjectStateReady
	}

	if err := h.repo.Update(r.Context(), id, existing); err != nil {
		apilog.WithFields(apilog.Fields{"project_id": id, "error": err.Error()}).Error("Failed to update project")
		writeError(w, http.StatusInternalServerError, "failed to update project: "+err.Error())
		return
	}

	apilog.WithField("project_id", id).Info("Project updated")
	writeJSON(w, http.StatusOK, existing)
}

// Delete fully removes a project: every Mongo collection, the Qdrant
// per-project schema-index collection, and (when the configured secret
// provider supports it) every secret stored under the project's
// namespace.
//
// External secret managers (GCP/AWS/Azure) intentionally do NOT have
// a server-driven delete path — those credentials must be cleaned
// up via the cloud console / IAM-audited tooling. The handler reports
// `secrets_skipped: true` in that case so the UI can surface the
// follow-up to the user.
//
// Pre-flight checks:
//   - 404 if the project doesn't exist
//   - 409 if a schema-indexing run is in flight (caller must cancel
//     first via /schema-index/cancel — auto-cancelling during a
//     destructive operation is too easy to misread)
//
// On success returns 200. The cascade is best-effort within the
// project: a Qdrant or secret failure logs but doesn't abort the
// Mongo cascade — a re-issued Delete is idempotent and finishes any
// step that didn't land.
//
// DELETE /api/v1/projects/{id}
func (h *ProjectsHandler) Delete(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if id == "" {
		writeError(w, http.StatusBadRequest, "project id is required")
		return
	}

	p, err := h.repo.GetByID(r.Context(), id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "get project: "+err.Error())
		return
	}
	if p == nil {
		writeError(w, http.StatusNotFound, "project not found")
		return
	}

	// 409 if indexing — the user must cancel through the dedicated
	// endpoint first. Auto-cancelling during a destructive op would
	// silently abort someone else's hour-long run.
	if p.SchemaIndexStatus == models.SchemaIndexStatusIndexing {
		writeError(w, http.StatusConflict, "schema indexing is in flight; cancel first via POST /api/v1/projects/"+id+"/schema-index/cancel before deleting the project")
		return
	}

	// Drop Qdrant collection (best-effort). On failure we log and
	// continue: BuildIndex drops on entry next time, so a leftover
	// collection isn't catastrophic — but the user gets the audit
	// log line so they know cleanup is partial.
	if h.dropper != nil {
		if err := h.dropper.DropCollection(r.Context(), id); err != nil {
			apilog.WithFields(apilog.Fields{"project_id": id, "error": err.Error()}).Warn("Project delete: Qdrant drop failed; cascade continues")
		}
	}

	// Sweep secrets ONLY when the configured provider implements
	// secrets.ProjectDeleter (mongodb-backed). External secret
	// managers (gcp/aws/azure) deliberately route deletion through
	// IAM-audited tooling — the API never reaches into them.
	secretsSkipped := true
	if h.secretProvider != nil {
		if del, ok := h.secretProvider.(secrets.ProjectDeleter); ok {
			if err := del.DeleteAllForProject(r.Context(), id); err != nil {
				apilog.WithFields(apilog.Fields{"project_id": id, "error": err.Error()}).Warn("Project delete: secret sweep failed; cascade continues")
			} else {
				secretsSkipped = false
			}
		}
	}

	if err := h.repo.DeleteCascade(r.Context(), id); err != nil {
		apilog.WithFields(apilog.Fields{"project_id": id, "error": err.Error()}).Error("Project delete: Mongo cascade failed")
		writeError(w, http.StatusInternalServerError, "delete cascade: "+err.Error())
		return
	}

	apilog.WithFields(apilog.Fields{"project_id": id, "secrets_skipped": secretsSkipped}).Info("Project deleted")
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"deleted":         id,
		"secrets_skipped": secretsSkipped,
	})
}
